INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit.fee', '充值手续费');
INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit.minimum', '最小充值金额');
INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'withdraw.fee', '取现手续费');
INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'withdraw.minimum', '最小取现金额');

INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit.fee', 'CNY', 0, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit.minimum', 'CNY', 0, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'withdraw.fee', 'CNY', 0, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'withdraw.minimum', 'CNY', 0, 1);

