INSERT USERS (USERNAME, TYPE, BIND_INFO) VALUES ('p2p', 'P2P', '{}');
INSERT USERS (USERNAME, TYPE, BIND_INFO) VALUES ('tail', 'TAIL', '{}');
INSERT USERS (USERNAME, TYPE, BIND_INFO) VALUES ('risk', 'RISK', '{}');
INSERT USERS (USERNAME, TYPE, BIND_INFO) VALUES ('p2p-investor-profit', 'P2P_INVESTOR_PROFIT', '{}');


INSERT ACCOUNTS (USER_ID, TYPE, BALANCE_AMOUNT, BALANCE_CURRENCY,  FROZEN_AMOUNT, FROZEN_CURRENCY)
  VALUES ((SELECT ID FROM USERS WHERE USERNAME = 'p2p'), 'POOL', 0, 'CNY', 0, 'CNY');
INSERT ACCOUNTS (USER_ID, TYPE, BALANCE_AMOUNT, BALANCE_CURRENCY,  FROZEN_AMOUNT, FROZEN_CURRENCY)
  VALUES ((SELECT ID FROM USERS WHERE USERNAME = 'tail'), 'POOL', 0, 'CNY', 0, 'CNY');
INSERT ACCOUNTS (USER_ID, TYPE, BALANCE_AMOUNT, BALANCE_CURRENCY,  FROZEN_AMOUNT, FROZEN_CURRENCY)
  VALUES ((SELECT ID FROM USERS WHERE USERNAME = 'risk'), 'POOL', 0, 'CNY', 0, 'CNY');
INSERT ACCOUNTS (USER_ID, TYPE, BALANCE_AMOUNT, BALANCE_CURRENCY,  FROZEN_AMOUNT, FROZEN_CURRENCY)
  VALUES ((SELECT ID FROM USERS WHERE USERNAME = 'p2p-investor-profit'), 'POOL', 0, 'CNY', 0, 'CNY');