UPDATE BIZ_PARAMS SET ACTIVE = 0 WHERE KEY_CODE = 'deposit.minimum' AND TYPE = 'MONEY';
UPDATE BIZ_PARAMS SET ACTIVE = 0 WHERE KEY_CODE = 'withdraw.minimum' AND TYPE = 'MONEY';

INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit.minimum', 'CNY', 0.01, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'withdraw.minimum', 'CNY', 0.01, 1);
